// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace HtmlTools
{
    internal sealed partial class Vsix
    {
        public const string Id = "8682fae0-2ce9-49ea-93b5-edc92c118e2a";
        public const string Name = "HTML Tools 2019";
        public const string Description = @"Productivity tools for the HTML editor";
        public const string Language = "en-US";
        public const string Version = "1.0.4.1";
        public const string Author = "Mads Kristensen";
        public const string Tags = "html, Intellisense";
    }
}
