// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace HtmlTools
{
    internal sealed partial class Vsix
    {
        public const string Id = "3cef2919-d8c7-4e9f-a809-5a0ba9c61fac";
        public const string Name = "HTML Tools 2019";
        public const string Description = @"Productivity tools for the HTML editor";
        public const string Language = "en-US";
        public const string Version = "1.0.1";
        public const string Author = "Mads Kristensen";
        public const string Tags = "html, Intellisense";
    }
}
